// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkesqtvmbtcxrekmflkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrZXNxdHZtYnRjeHJla21mbGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzMxNDYsImV4cCI6MjA3MDc0OTE0Nn0.dqQ26_Quid7aulnjEK7ESrV0SaGAId2kHo_WrpwRhwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});